import { Component, EventEmitter, Output } from '@angular/core';
import { Usecase } from '../shared/usecase.model';

@Component({
  selector: 'app-use-case-library',
  templateUrl: './use-case-library.component.html',
  styleUrls: ['./use-case-library.component.css']
})
export class UseCaseLibraryComponent{

  @Output() newFav: EventEmitter<Usecase> = new EventEmitter();
  @Output() newUnfav: EventEmitter<Usecase> = new EventEmitter();

  useCases: Usecase[] = [
    new Usecase('Secondary Use Health Data', 'The report, researched and produced by the Open Data Institute (ODI), focuses on the importance of secondary use of health data in Europe to help respond to the many urgent challenges facing society and economy today. It states that by reusing health data in different ways, we can increase the value of this data and help to enable improvements in population health, more efficient healthcare systems, and foster innovation. The report identifies 22 key policy components needed to achieve a trusted and trustworthy data ecosystem and provides an evaluation of the quality of policy activity for each component. The report is independent work by the ODI that was commissioned by Roche.',['Open Data Institute'], {name: 'Mark Boyd', email:'policy@theodi.org'}, ['Health'], '2021', null, ['Other'], ['Processed data'], ['Generated'], ['Sensitive'], ['PII-relevant'], ['Individual'], ['Static', 'Up-to-date', '(Near-) realtime'], ['Social & Ecological', 'Economic'], ['Same industry'], ['Service', 'Data'], null, null, null, ['Legal', 'Organizational', 'Semantic', 'Technical'], null, ['Continuous'], ['Secondary'], ['Many-to-many'], ['Efficiency gains', 'Improved quality', 'New insights', 'New offerings'], null, null),
    new Usecase('Smart Cleaning', 'The use case is about smart cleaning and it discusses the agreements that are needed to support it. These agreements are necessary when scaling the use case to more data sources, actors, and applications of the data. These agreements are needed to ensure trust and interoperability between actors. The use case also mentions that in order to enable a scalable and interoperable system, agreements between actors need to be co-created, updated, and actors’ adherence to these agreements must be monitored. Additionally, the use case mentions that with more actors, sensors, and applications of data, a more granular restriction of access will be required, as not all actors should receive all data.',['Data Sharing Coalition', 'FacilityApps', 'AMdEX'], {name: 'Data Sharing Coalition', email: 'info@datasharingcoalition.eu'}, ['Facility Management'], '2021', ' ', ['Process'], ['Processed data'], ['Customer-provided'], ['Confidential'], ['Non-PII-relevant'], ['Organizational'], ['(Near-) realtime'], ['Economic'], ['Cross-industry'], ['Financial'], null, ['Data consumer'], ['Closed API'], ['Technical'], ['Agreement-based'], ['Continuous'], ['Primary'], ['Many-to-one'], ['Efficiency gains'], ['Consumer-initiated'], ['Consumer-controlled']),
    new Usecase('The value of sharing data in regulated environments', 'This is a case study of how sharing data can benefit a business in regulated environments. Sharing data is a legal requirement in some industries and can also provide benefits beyond compliance, such as creating new business models and reducing costs. Barclays complies with the Second Payment Services Directive (PSD2) and open banking regulations, which allows banking customers to easily share personal data between authorized organizations online. Beyond implementation, Barclays developed a consumer-focused data aggregation tool and works with fintech startups to drive innovation.', ['Barclays', ' Open Data Institute'], {name: 'Open Data Institute', email: 'info@theodi.org'}, ['Banking', ' Finance'], '2020', 'https://theodi.org/article/case-study-the-value-of-sharing-data-in-regulated-environments/', ['Other'], ['Processed data'], ['Customer-provided'], ['Sensitive'], ['PII-relevant'], ['Organizational'], ['Up-to-Date'], ['Legal', 'Economic'], ['Same industry'], ['Other', 'Financial', 'Reputation'], null, ['Service broker'], ['Open API'], ['Legal', 'Semantic'], ['Agreement-based'], ['On demand'], ['Secondary'], ['One-to-many'], ['New offerings'], null, ['Service broker-controlled']),
    new Usecase('The value of sharing data forbenchmarking and insights', 'HiLo Maritime Risk Management is a joint industry initiative aimed at improving risk modeling in the shipping industry by aggregating data on near misses, accidents, and incidents. By analyzing the data, HiLo provides individual shipping companies with safety recommendations and helps to reduce the number of accidents. The shipping industry faces a high rate of incidents, and HiLos goal is to support companies in operating more safely and reducing the impact of accidents on the economy, environment, and society. To be successful, data sharing is essential and independent organizations can act as a trusted intermediary to manage and analyze data on behalf of the sector.', ['HiLo Maritime Risk Management', ' Open Data Institute'], {name: 'Open Data Institute', email: 'info@theodi.org'}, ['Maritime', ' Shipping'], '2020', 'https://theodi.org/article/case-study-the-value-of-sharing-data-for-benchmarking-and-insights/', ['Process', 'Environment'], null, ['Generated'], ['Confidential'], ['Non-PII-relevant'], ['Organizational'], ['(Near-) realtime'], ['Social & Ecological', 'Economic'], ['Same industry'], ['Financial', 'Service'], null, ['Intermediary'], ['Closed API'], null, ['Agreement-based'], ['Continuous'], ['Secondary'], ['Many-to-many'], ['Efficiency gains', 'New insights'], null, null),
    new Usecase('Secure and trusted data exchange: German Edge Clouds ONCITE', 'German Edge Clouds ONCITE is a solution for secure and trusted data exchange in the supply chain. It allows companies to store and process data on site, before exchanging it over a public cloud while ensuring data sovereignty. The IDS Connector is a user interface that allows partners to monitor and control data exchange transactions. Each IDS participant can decide who is allowed to view its data, use it, and at what cost.', ['German Edge Cloud'], {name: 'Bernd Fondermann', email: 'contact@brainlounge.de'}, ['IT services'], '2020', 'https://internationaldataspaces.org/secure-and-trusted-data-exchange-german-edge-clouds-oncite-is-ids-ready/', ['Process', 'Product'], null, ['Generated'], ['Confidential'], ['Non-PII-relevant'], ['Organizational'], null, ['Economic'], ['Same industry'], ['Data', 'Financial'], null, ['Intermediary'], ['Closed API'], ['Legal', 'Semantic'], ['Agreement-based'], null, ['Secondary'], ['Many-to-many'], ['Efficiency gains', 'Improved quality', 'New insights'], null, ['Intermediary-controlled']),
    new Usecase('Sharing data to improve safety at sea', 'The Open Marine Data project is aimed at improving access to data collected by emergency responders in the marine sector and to provide an open marine dataset for use by the whole sector. The challenge is the mismatch in data being shared between the relevant agencies, which does not always happen efficiently. The project is led by the GeoData Institute at the University of Southampton and is funded by the Lloyd’s Register Foundation through the Open Data Institute (ODI). The team is addressing the issue by improving data sharing between the Maritime and Coastguard Agency (MCA) and the Royal National Lifeboat Institute (RNLI) and creating a blueprint for an open marine incident dataset.', ['GeoData Institute', ' MCA', ' RNLI', ' Llodys Register Foundation', ' Open Data Institute'], {name: 'Open Data Institute', email: 'info@theodi.org'}, ['Maritime', ' Shipping', ' Emergency response'], '2021', 'https://theodi.org/article/case-study-sharing-data-to-improve-the-safety-of-lives-at-sea/', ['Process', 'Environment'], ['Modified data'], ['Generated'], ['Confidential'], ['Non-PII-relevant'], ['Organizational'], ['(Near-) realtime'], ['Social & Ecological'], ['Same industry'], ['Data', 'Service', 'Other'], null, null, ['Closed API'], ['Legal', 'Semantic', 'Technical'], ['Agreement-based'], ['Continuous'], ['Primary'], ['Many-to-many'], ['Efficiency gains'], null, null),
    new Usecase('The value of sharing data for improving market reach', 'Everyone Active, a UK leisure operator, is sharing data about its products and services to reach new customers and improve market reach. The data shared is open, standardised and includes information on physical activities such as fitness classes, swimming sessions and tennis court availability. The approach has already led to an increase of 11,500 customers and 36% of these were previously not customers of Everyone Active. This data sharing helps businesses work with third-parties to create discovery tools and complementary products, supporting the growth of the leisure and activity sector.', ['Everyone Active', ' Open Data Institute'], {name: 'Open Data Institue', email: 'info@theodi.org'}, ['Leisure'], '2020', 'https://theodi.org/article/case-study-the-value-of-sharing-data-for-improving-market-reach/', ['Product'], ['Raw data'], ['Customer-provided'], ['Public'], ['Non-PII-relevant'], ['Organizational'], ['Up-to-Date'], ['Economic'], ['Same industry'], ['Financial'], null, ['Intermediary'], ['Open API'], ['Semantic'], ['Open'], ['Event-based'], ['Primary'], ['One-to-many'], ['Efficiency gains', 'New offerings'], null, null),
    new Usecase('Maritime Data Space', 'MDS (Maritime Data Exchange and Sharing Ecosystem) aims to develop an open framework for the secure and efficient exchange of ship-related data among stakeholders in the maritime industry. The MDS platform extends and enhances the IDS (Industrial Data Space) architecture to provide unambiguous data ownership and the ability for data to be stored and accessed from multiple locations. The platform views ship data as a product in itself, with data ownership and governance determined by the data owner. This allows for safe and secure comparisons, trending, and benchmarking of large data sets without infringing on data owners confidentiality.', ['Sintef'], {name: 'Dag Atle Nesheim', email: 'dag.atle.nesheim@sintef.no'}, ['Maritime', ' Shipping'], '2021', 'https://www.sintef.no/projectweb/maritime-data-space-mds/about/', ['Other'], ['Raw data', 'Processed data'], ['Generated'], ['Confidential'], ['Non-PII-relevant'], ['Organizational'], ['Up-to-Date', '(Near-) realtime'], ['Economic'], ['Same industry'], ['Other'], null, ['Intermediary'], ['Platform'], ['Legal'], ['Agreement-based'], ['On demand'], ['Secondary'], ['Many-to-many'], ['Efficiency gains', 'New insights'], null, ['Provider-controlled']),
    new Usecase('Open Manufacturing Platform', 'Microsoft and the BMW Group have partnered on the Open Manufacturing Platform (OMP) initiative, designed to support the development of smart factory solutions across the automotive and manufacturing sectors. The platform is built on Microsofts Azure industrial IoT cloud platform and provides a reference architecture with open source components based on open industrial standards and an open data model. The OMP intends to address common industrial challenges such as machine connectivity and on-premises systems integration, unlocking the potential of data for community members to build and integrate industrial solutions more quickly and securely. The OMP Advisory Board will be in operation with an initial set of four to six partners in place by the end of 2019.', ['Microsoft', ' BMW'], {name: 'Michael Ortmeier', email: 'michael.ortmeier@bmw.de'}, ['Automotive', ' Manufacturing'], '2019', 'https://news.microsoft.com/2019/04/02/microsoft-and-the-bmw-group-launch-the-open-manufacturing-platform/', ['Other'], null, ['Customer-provided'], ['Internal'], ['Non-PII-relevant'], ['Organizational'], ['Up-to-Date'], ['Economic'], ['Cross-industry'], ['Data'], null, ['Data-provider', 'Data consumer'], ['Platform'], null, ['Agreement-based'], ['On demand'], ['Secondary'], ['Many-to-many'], ['Efficiency gains', 'New insights', 'Improved quality'], ['Consumer-initiated'], ['Provider-controlled']),
    new Usecase('Mobility and proximity in Canada during COVID-19', 'The  COVID-19  pandemic  caused  severe  disruptions  on  movement  across  Canada  but,  for  many  policymakers  and  members  of  the  public,  it  was  unclear  how  severe,  dispersed,  and  lasting  these  disruptions  were.  To  fill  this  information  gap,  researchers  at  the  University  of  Toronto  formed  a  data  collaborative  with  Cuebiq  (a  co-author  of  this  report)  and  the  ISI  Foundation  in  which  Cuebiq  provided  data  on  the  geolocation  of  smartphone  devices  across Canada while the ISI Foundation provided code that the research team adapted to a Canada-specific context. The  research  team  used  these  inputs  to  calculate  the  proximity  and  mobility  of  devices.  The  subsequent  analysis  revealed  that,  while  mobility  in  Canada  increased  in  the  months  after  lockdowns  took  effect,  proximity  between  individuals remained low.', ['The Gov Lab', ' cuebiq', ' Open Data Institute'], {name: 'Open Data Institute', email: 'info@theodi.org'}, ['Health'], '2021', 'https://theodi.org/wp-content/uploads/2021/04/1-Mobility-and-Proximity-in-Canada_0329_v2.pdf', ['Human'], ['Processed data'], ['Customer-provided'], ['Sensitive'], ['PII-relevant'], ['Individual'], ['Up-to-Date'], ['Social & Ecological'], null, ['Reputation'], ['Free'], null, null, ['Legal'], ['Agreement-based'], ['On demand'], ['End use'], ['One-to-one'], ['New insights'], null, ['Provider-controlled']),
    new Usecase('Developing a Data Cooperative Model for small Energy Cooperatives', 'Open Data Manchester worked with the Carbon Co-op to study the potential of data cooperatives. The aim was to empower people to take control of their data, offer choice, and build trust in data sharing. Data cooperatives can improve organizational efficiency and save money, but require trust, resources, and technical understanding to be sustainable. The COVID-19 pandemic had an impact on the project, but the co-design workshops still took place virtually.', ['Open Data Manchester', ' Carbon Co-op', ' Open Data Institute'], {name: 'Open Data Manchester', email: 'oda@greatermanchester-ca.gov.uk.'}, ['Energy'], '2021', 'https://drive.google.com/file/d/1qCB1yEayDmFq_laL3E8EdzAE6pvRIkXg/view', ['Other'], null, ['Customer-provided'], ['Sensitive'], ['PII-relevant'], ['Individual'], ['Up-to-Date'], null, ['Intra-organizational', 'Same industry', 'Cross-industry'], null, null, ['Intermediary'], ['Platform'], ['Legal'], ['Agreement-based'], null, null, null, null, null, ['Intermediary-controlled']),
    new Usecase('The value of sharing data to drive open innovation', 'The case study is about the EU-funded Data Pitch open innovation program that helps corporate and public sector organizations share data with startups and SMEs to solve business challenges. The program uses operational data to help external organizations analyze and use that data to provide insights and identify efficiency savings. The case study focuses on the collaboration between Greiner Packaging International and OBUU, a logistics insight company. By sharing data, OBUU was able to analyze the three key performance indicators of Greiners supply chain and identify a potential reduction in fixed asset investment of around 35%, resulting in a significant cost saving for the business.', ['Greiner Packaging International', ' OBUU', ' Open Data Institute'], {name: 'Open Data Institute', email: 'info@theodi.org'}, ['Logistics'], '2020', 'https://docs.google.com/document/d/13TLmY6_wzFQpUiiL1ItHHiOgLQh59NMJlMUaXy93DmQ/edit', ['Process'], null, ['Generated'], ['Confidential'], ['Non-PII-relevant'], ['Organizational'], ['Static'], ['Economic'], ['Intra-organizational'], ['Service', 'Financial'], null, ['Data-provider'], null, ['Legal'], ['Agreement-based'], ['On demand'], ['Secondary'], ['One-to-one'], ['Efficiency gains', 'New insights'], null, null),
    new Usecase('R&D Stimulus Fund', 'The report focuses on two themes: improving data sharing in the energy sector using CKAN, an open-source data management platform, and exploring economic sustainability for nonprofits. The report explains how the use of CKAN has improved data sharing in the UK energy sector by making it easier for data owners to create and maintain metadata for their datasets. The second theme of the report looks at the economic sustainability of organizations in the field, presenting the Green Web Foundation as a case study and comparing its approach to funding with that of the organization behind the report.', ['Open Climate Fix'], {name: 'Florian Wirtz', email: 'info@openclimatefix.org'}, ['Energy'], '2021', 'https://theodi.org/article/open-climate-fix-making-the-electricity-grid-more-efficient-through-open-data/', ['Process', 'Environment'], ['Enriched data'], ['Generated'], ['Public'], ['Non-PII-relevant'], ['Organizational'], ['Static'], ['Social & Ecological', 'Economic'], ['Same industry'], ['Other'], null, ['Intermediary'], ['Open API'], ['Organizational'], null, null, ['Secondary'], ['Many-to-many'], ['Efficiency gains'], null, null),
    new Usecase('Recruiting Cloud Platform Based on IDS Connectors', 'SCOPE and idento.one are companies that have partnered to offer secure e-recruiting solutions that comply with the EU General Data Protection Regulation (GDPR). SCOPE is an e-recruiting software that allows companies to publish job ads, view and process all applications received, and sort all information properly. The International Data Spaces Association (IDSA) has developed the IDS standard for secure data transmission, which SCOPE and idento.one aim to offer to clients for transparency and legal certainty when handling personal data. Candidates can determine who has access to their data through IDS connectors and can revoke permission at any time.', ['idento.one', ' SCOPE', ' International Data Spaces Association'], {name: 'Hannes Bauer', email: 'info@orbiter.de'}, ['Recruiting'], '2020', 'https://internationaldataspaces.org/recruiting-cloud-platform-based-on-ids-connectors/', ['Human'], ['Modified data'], ['Customer-provided'], ['Sensitive'], ['PII-relevant'], ['Individual'], ['Up-to-Date'], ['Legal'], ['Cross-industry'], ['Other'], null, ['Intermediary'], ['Platform'], ['Legal'], ['Agreement-based'], ['On demand'], ['Primary'], ['One-to-one'], null, null, ['Intermediary-controlled']),
    new Usecase('Sharing freight transport data with Insurers', 'The use of digital waybills (e-CMR) is growing, allowing new products and services in and outside the logistics sector. In this use case, the Insured Party gives permission to the Insurer in case of a claim to retrieve e-CMR data from the e-CMR provider to improve claim handling. The data sharing context is limited in standardization and the Insured Party needs control over the data. iSHARE offers a mechanism for identification, authentication, and authorization which allows the Insured Party to control their data. The increased adoption of e-CMR and standardization of its exchange is expected to make this use case more attractive to Insurers in the coming years.', ['iShare', ' Data Sharing Coalition'], {name: 'Data Sharing Coalition', email: 'info@nlaic.com'}, ['Logistics', ' Insurance'], '2021', 'https://datasharingcoalition.eu/app/uploads/2021/06/210603-final-deliverable-use-case-ishare-vvv.pdf', ['Process'], ['Processed data'], ['Customer-provided'], ['Sensitive'], ['Non-PII-relevant'], ['Organizational'], ['Static'], ['Economic'], ['Same industry'], ['Financial'], null, ['Data consumer'], ['Platform'], ['Legal'], ['Agreement-based'], ['Event-based'], ['Primary'], ['Many-to-many'], ['Efficiency gains'], null, null),
    new Usecase('The value of sharing data in supply chain optimisation', 'In this case study, Airbus shares engineering data with its supply chain partners to improve the efficiency and accuracy of its product design as part of a project exploring the value of data sharing in the private sector. Airbus, along with its partners, has developed the Advanced Product Concept Analysis Environment (APROCONE) platform to enhance the sharing of aircraft design data and improve the integrated product design process. The platform helps improve the speed, accuracy and efficiency of the product design process and reduces development costs by enabling real-time data sharing. Benefits include improved collaboration, reduced administration costs, better cost management and increased transparency and provenance of the supply chain.', ['Airbus', ' Open Data Institute'], {name: 'Open Data Institute', email: 'info@theodi.org'}, ['Aerospace', ' Manufacturing'], '2020', 'https://docs.google.com/document/d/1B3VnH73JYE2zx1NjSivrFpvFbKWAjt5cnIbsWp98_bI/edit', ['Product', 'Process', 'Environment'], null, ['Generated'], ['Confidential'], ['Non-PII-relevant'], ['Organizational'], ['(Near-) realtime'], ['Economic', 'Social & Ecological'], ['Same industry'], ['Service', 'Financial', 'Data'], null, ['Intermediary'], ['Platform'], ['Semantic'], ['Agreement-based'], ['Continuous'], ['Primary'], ['Many-to-many'], ['Efficiency gains', 'Improved quality', 'New insights'], null, ['Intermediary-controlled']),
    new Usecase('Monitoring Human Trafficking', 'Human trafficking affects over 40 million people globally. Lack of data collaboration is a hindrance to combating human trafficking due to legal and trust barriers. Multi-party computation (MPC) can reduce these barriers and a scalable design for MPC-based data collaboration was created to improve the monitoring of sexual exploitation.', ['Sustainable Rescue', ' Pinsent Masons', ' RosemanLabs', ' Data Sharing Coalition'], {name: 'Data Sharing Coalition', email: 'info@nlaic.com'}, ['Law enforcement'], '2022', 'https://datasharingcoalition.eu/use-cases/improved-monitoring-of-human-trafficking-by-sharing-insights/', ['Human'], ['Modified data'], null, ['Sensitive'], ['PII-relevant'], ['Organizational'], ['Up-to-Date'], ['Legal'], ['Cross-industry'], ['Other', 'Data'], null, ['Service broker'], null, ['Legal', 'Organizational'], ['Agreement-based'], ['On demand'], ['Secondary'], ['Many-to-many'], ['Efficiency gains', 'New insights'], null, ['Service broker-controlled']),
    new Usecase('The value of sharing data to build trust', 'Sharing data can help businesses in building trust and credibility. A case study of the agriculture sector company Syngenta showed that it shared open data to demonstrate its commitment to being a trustworthy organization. The benefits of this approach for Syngenta have been improved reputation, better connections in adjacent sectors, and better engagement with supply chain partners. Sharing data on sustainability goals and wider research has helped Syngenta create a virtuous cycle of increased understanding, improved economic and environmental outcomes and others in the sector to share data.', ['Syngenta', ' Open Data Institute'], {name: 'Open Data Institute', email: 'info@theodi.org'}, ['Agriculture'], '2020', 'https://docs.google.com/document/d/1moXsFh2fHV6aqXWxZ1eOuKsgGZcksFPk/edit#heading=h.gjdgxs', ['Other'], ['Processed data'], ['Generated'], ['Public'], ['Non-PII-relevant'], ['Organizational'], ['Up-to-Date'], ['Social & Ecological', 'Economic'], ['Cross-industry'], ['Reputation', 'Service', 'Financial'], ['Free'], ['Intermediary'], ['Platform'], ['Semantic'], ['Open'], ['On demand'], ['End use'], ['One-to-many'], ['New insights'], null, ['Provider-controlled']),
    new Usecase('Volvo Cars', 'Volvo Cars is using ShareAspace, a secure product lifecycle management (PLM) collaboration software, to manage multiple collaboration projects, outsource complex assignments, securely share technology with other original equipment manufacturers (OEMs) and system suppliers, and easily establish and terminate collaborations. ShareAspace maintains part information and is delivered as a hosted cloud service, integrating with a variety of software to present a common view of relevant data. It allows organizations to share information securely across company borders and engineering processes, is standards-based and open, and offers a fast return on investment.', ['Volvo', ' ShareAspace '], {name: 'ShareAspace', email: 'info@eurostep.com'}, ['Automotive', ' Manufacturing'], '2021', 'https://www.eurostep.com/volvo-cars-handling-product-data-management-to-streamline-collaboration-between-organisations/', ['Process', 'Product'], null, ['Generated'], ['Confidential'], ['Non-PII-relevant'], ['Organizational'], ['Up-to-Date'], ['Economic'], ['Same industry'], ['Financial', 'Service'], null, ['Service broker'], ['Closed API'], ['Semantic', 'Organizational'], ['Agreement-based'], ['On demand'], ['Primary'], ['Many-to-many'], ['Efficiency gains'], null, ['Service broker-controlled']),
    new Usecase('The WAter Incident Database', 'The WAter Incident Database (WAID) is a service developed by the National Water Safety Forum (NWSF) to bring together water-related incident data from multiple sources in the UK. Its goal is to provide evidence for drowning prevention activities and to provide better insights into risk levels to reduce drowning fatalities. The current iteration of the database is being descoped and the WAID team is developing a new version to shift its priorities towards saving lives.', [' National Water Safety Forum', ' Open Data Institute'], {name: 'Open Data Institute', email: 'info@theodi.org'}, ['Maritime', ' Emergency response'], '2022', 'https://theodi.org/article/the-water-incident-dataset-waid-saving-lives-with-collaborative-water-data/', ['Human', 'Environment'], ['Processed data'], ['Generated'], ['Confidential'], ['PII-relevant'], ['Organizational'], ['Up-to-Date'], ['Social & Ecological'], ['Same industry'], ['Data', 'Service', 'Other'], null, ['Service broker'], ['Closed API'], ['Semantic', 'Organizational'], ['Agreement-based'], ['Event-based'], ['Secondary'], ['Many-to-many'], ['Efficiency gains', 'New insights'], null, ['Service broker-controlled']),
    new Usecase('Weed Robot', 'The use of IoT data is growing in importance in agriculture, as it can provide valuable insights for various applications. The use case described focuses on using shared IoT data to address the issue of "volunteer potato" weeds in a cost-effective manner. Harmonization of data services and low-latency data exchange infrastructure are critical components in the design of this use case.', ['AgroIntelli', ' kpn', ' Data Sharing Coalition'], {name: 'Data Sharing Coalition', email: 'info@nlaic.com'}, ['Agriculture'], '2021', 'https://datasharingcoalition.eu/app/uploads/2021/06/210610-final-deliverable-use-case-weed-robot.pdf', ['Environment'], ['Raw data'], ['Customer-provided'], ['Confidential'], ['Non-PII-relevant'], ['Organizational'], ['(Near-) realtime'], ['Economic'], ['Same industry'], ['Service'], null, ['Intermediary'], ['Platform'], ['Semantic'], ['Agreement-based'], ['Continuous'], ['Primary'], ['One-to-one'], ['Efficiency gains'], null, null),
    new Usecase('Your Dsposal', 'This report discusses the development of an open data standard for Household Waste Recycling Centers (HWRCs) over 8 months through desk research and stakeholder workshops. The authors believe that open data standards are important for the waste industry to improve resource efficiency, reduce environmental impact and meet carbon budgets. The authors hope that this standard will be a first step in establishing an open data institution and unlocking opportunities and innovation through the development of open data infrastructure. Global technology institutions have shown interest in using the data, and the authors acknowledge that open data and standards can provide a foundation for collaboration to address the climate emergency.', ['Your Dsposal'], {name: 'Sophie Walker', email: 'sophie@yourdsopsal.uk'}, ['Recycling', ' Waste'], '2021', 'https://dsposal.uk/your/articles/open3r', ['Other'], null, ['Generated'], ['Confidential'], ['Non-PII-relevant'], ['Organizational'], ['Up-to-Date'], ['Social & Ecological'], ['Cross-industry'], ['Other'], null, null, null, ['Organizational', 'Semantic'], null, ['On demand'], ['Primary'], ['One-to-many'], ['Efficiency gains'], null, null),
    new Usecase('Airbus APROCONE', 'The value of sharing data in supply chain optimization is the subject of a case study in the aerospace sector, exploring the concept of data sharing in the private sector. The study looks at how Airbus shares engineering data on its airplane concepts with supply chain partners to improve efficiency and accuracy of its product design. The proof of concept co-design platform developed within APROCONE, a collaborative research project involving Airbus and partners, is intended to help improve the design process in the aerospace supply chain by allowing partners to access, use, and share data in real time. The platform enhances the sharing of aircraft and engine design data among partners to improve integrated product design and reduce development costs, as well as increase supply chain efficiency.', ['Airbus', ' Centre for Modelling and Simulation (CFMS)', ' GKN Aerospace', 'MSC Software', ' Rolls-Royce', ' Cranfield University', ' University of Cambridge'], {name: 'Open Data Institute', email: 'info@theodi.org'}, ['Aerospace'], '2020', 'https://www.theodi.org/article/case-study-the-value-of-sharing-data-in-supply-chain-optimisation/', ['Product'], null, null, ['Confidential'], ['Non-PII-relevant'], ['Organizational'], ['(Near-) realtime'], ['Economic'], ['Intra-organizational', 'Cross-industry'], ['Financial'], null, ['Intermediary'], ['Platform'], ['Technical'], ['Agreement-based'], ['On demand'], ['Primary'], ['Many-to-many'], ['Efficiency gains', 'Improved quality'], ['Consumer-initiated'], null),
    new Usecase('Bedrock for better public infrastructure in Honduras', 'The public infrastructure sector in Honduras has been plagued with corruption, but recent legislative reforms have mandated public entities to publish information about their infrastructure contracts through a centralized database called SISOCS. The government has adopted the Open Contracting Data Standard to refine the quality and completeness of their data. As a result, transparency in the sector has improved dramatically, with 95% of the information now being disclosed, compared to just 27% in 2014. CoST Honduras, a local anti-corruption watchdog, has trained citizens to monitor infrastructure projects and has developed a Multi-Stakeholder Group that leads the assurance process, tracking the progress of projects and holding entities accountable. The increased data and citizen involvement has increased trust and has paved the way towards a new culture of public spending in the public eye.', ['CoST- the Infrastructure Transparency Initiative'], {name: 'Open Contracting', email: 'info@open-contracting.org'}, ['Public Infrastructure'], '2019', 'https://medium.com/open-contracting-stories/bedrock-for-better-public-infrastructure-in-honduras-1e39526100a5', ['Other'], ['Enriched data'], ['Generated'], ['Public'], ['Non-PII-relevant'], ['Shared'], ['Up-to-Date'], ['Social & Ecological', 'Economic', 'Legal'], null, ['Other'], ['Free'], ['Intermediary'], ['Platform'], ['Organizational'], ['Open'], ['Continuous'], ['Primary'], ['One-to-many'], ['New insights'], null, ['Consumer-controlled']),
    new Usecase('Benchmarking for Industry Associations', 'Industry Associations (IAs) use data from their members to create benchmarks that communicate the performance of the sector and provide organizations with insights on their relative performance compared to peers. Currently, businesses must submit data manually, which is time-consuming and can lead to inaccuracies. Qualified and standardized data is available from Service Providers, but it is not being used for benchmarking purposes. The SBR Nexus, a data sharing initiative, has initiated a use case to make it easier for organizations to share data and allow it to be reused for benchmarking. Multiple Industry Associations have been involved in the use case through interviews.', ['Data Sharing Coalition'], {name: 'Data Sharing Coalition', email: 'info@datasharingcoalition.eu'}, ['Multiple Industries'], '2021', 'https://datasharingcoalition.eu/app/uploads/2021/05/210525-report-findings-use-case-benchmarking-for-industry-associations.pdf', ['Process'], ['Processed data'], ['Generated'], ['Sensitive'], ['Non-PII-relevant'], ['Organizational'], ['Up-to-Date'], ['Economic'], ['Same industry'], ['Other'], null, ['Data consumer'], ['Closed API'], ['Legal', 'Semantic'], ['Agreement-based'], ['On demand'], ['Primary'], ['One-to-one'], ['New insights'], ['Consumer-initiated'], ['Provider-controlled']),
    new Usecase('COVID-19 Mobility Data Network’s Use of Facebook Data', 'In April 2020, Facebook expanded its Data for Good offerings to support the fight against COVID-19. The companys Movement Range Maps, Co-Location Maps, and other Data for Good products incorporate mobility data that have been used for monitoring physical distancing, identifying high-risk areas for disease spread, and other issues. One of the largest mobility data collaborations created this year was the global COVID-19 Mobility Data Network, which was used by decision-makers at the national, regional and local level for monitoring physical distancing and informing mobility restrictions. The COVID-19 Mobility Data Network is a data pool collaboration between Facebook, Cuebiq, and Camber Systems, and each partner follows a Data Use Policy for data use, privacy, and ethics.', ['Facebook', ' Open Data Institute', ' Quebiq', ' The Gov Lab'], {name: 'Open Data Institute', email: 'info@theodi.org'}, ['Public Institutions'], '2021', 'https://theodi.org/wp-content/uploads/2021/04/5-COVID-19-Mobility-Data-Networks-Use-of-Facebook-Data_v2.pdf', ['Human'], ['Processed data'], ['Generated'], ['Sensitive'], ['PII-relevant'], ['Organizational'], ['(Near-) realtime'], ['Social & Ecological'], ['Cross-industry'], ['Other'], ['Free'], ['Intermediary'], ['Platform'], ['Legal'], ['Agreement-based'], ['Continuous'], ['Primary'], ['Many-to-many'], ['New insights'], null, null),
    new Usecase('DCC Data for Good: Achieving net zero through smart meter data access', 'The Data Communications Company (DCC) is a licensed monopoly responsible for the design, delivery, and management of the smart meter system in Great Britain. The goal of DCCs data access initiative, called Data for Good, is to improve access to smart meter system data and work with organizations to address challenges facing the UK, such as reaching net zero and reducing fuel poverty. The Open Data Institute has been working with DCC to provide expert guidance, practical tools, and connections to help explore opportunities and barriers in improving data access in the smart meter ecosystem. The UK Smart Meter Data Ecosystem is a key part of the data infrastructure needed to achieve a sustainable future energy market, and requires responsible governance, strong security, and a culture of innovation to realize its potential benefits.', ['Data Communications Company', ' Open Data Institute'], {name: 'Open Data Institute', email: 'info@theodi.org'}, ['Energy'], '2022', 'https://theodi.org/article/dcc-data-for-good-achieving-net-zero-through-smart-meter-data-access', ['Human'], ['Enriched data'], ['Generated'], ['Sensitive'], ['PII-relevant'], ['Shared'], ['Up-to-Date'], ['Social & Ecological', 'Economic'], null, ['Other'], ['Free'], ['Intermediary'], ['Platform'], ['Technical'], ['Trust-based'], ['Continuous'], ['Primary'], ['Many-to-many'], ['Efficiency gains', 'New insights'], null, ['Intermediary-controlled']),
    new Usecase('Digital platform for industrial 3D printing', 'Thyssenkrupp is a German industrial group offering consulting and design services for additive manufacturing. The growing use of additive manufacturing in various industries poses challenges for data protection and protection of intellectual property. To address these challenges, thyssenkrupp has developed a digital additive manufacturing platform in partnership with IBM, using IDS technology and IBM Blockchain. The platform aims to increase automation, efficiency, safety, and expertise in additive manufacturing. The platform is based on the Linux Foundation’s Hyperledger Fabric for traceability and immutability and IDS for secure data transfer.', ['Thyssenkrupp', ' IBM'], {name: 'Joachim Stumpfe', email: 'joachim.stumpfe@thyssenkrupp.com'}, ['Manufacturing'], '2019', 'https://www.ibm.com/blogs/blockchain/2019/04/digital-platform-for-industrial-3d-printing/', ['Product'], ['Processed data'], ['Customer-provided'], ['Sensitive'], ['Non-PII-relevant'], ['Organizational'], ['Static'], ['Economic'], ['Cross-industry'], ['Financial'], ['Usage-based'], ['Intermediary'], ['Platform'], ['Legal', 'Technical'], ['Application-based'], ['On demand'], ['Primary'], ['One-to-many'], ['Efficiency gains'], null, null),
    new Usecase('A systems-approach to data can help install trust and enable a net zero future', 'The Paris Agreement, signed in 2016 under the UNFCCC, aims to limit the global average temperature increase to less than 2°C above pre-industrial levels. DNVs Energy Transition Outlook forecasts that hydrogen and Carbon Capture and Storage (CCS) will play a crucial role in reaching these climate goals. In order for the UK governments CCS business model to be successful, it will need to be profitable for the industry and have transparent data provenance. The success of the CCS and Hydrogen industries will also depend on ensuring high data quality and validating the provenance and veracity of derived data. The emergence of independent data trusts is expected to play a role in curating and extracting value from data for the benefit of stakeholders.', ['DNV', ' Open Data Institute'], {name: 'DNV', email: 'null'}, ['Energy'], '2021', 'https://www.dnv.com/publications/how-a-systems-approach-to-data-can-install-trust-and-enable-a-net-zero-future-201552', ['Environment'], ['Enriched data'], ['Generated'], null, null, ['Organizational'], null, ['Economic', 'Social & Ecological'], ['Cross-industry'], null, null, null, null, null, null, null, null, null, null, null, null),
    new Usecase('ERT Expert Paper – B2B Data Sharing', '(Since this paper contains multiple smaller Use Cases, there are no Use Case characteristics to filter) Business to Business (B2B) data sharing involves making data available to or accessing data from other companies for business purposes. The benefits of B2B data sharing include developing and enriching services, training artificial intelligence (AI), improving customer experience, boosting operational efficiency, and differentiating products and services. Europe has the opportunity to lead in B2B data sharing but there are challenges like legal and data privacy issues and lack of common standards. Successful B2B data sharing models are built on four essential pillars: a reference architecture based on infrastructure standards, common data standards and governance rules, B2B marketplaces for data, and data analytics and AI. ERT believes that the EU should facilitate voluntary sharing of B2B data and strike a balance between protecting privacy and stimulating research and development. The EUs Data Strategy provides a foundation for fostering B2B data sharing and should be the priority for execution.', ['European Round Table for Industry'], {name: 'European Round Table for Industry', email: 'contact@ert.eu'}, ['Multiple industries'], '2021', 'https://ert.eu/documents/ert-expert-paper-b2b-data-sharing/', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null),
    new Usecase('Facility Apps - Smart Cleaning', 'Building sensor data is being increasingly used for the development of smart products and services. Using sensor data can enable more effective and efficient cleaning and facility services. The European Cleaning and Facility Services Industry is the largest sectoral employer in Europe, and is looking to increase efficiency and effectiveness through the use of sensors. In this use case, sensor data from dispensers and people counters is shared to develop smart cleaning services. The use case leads to efficiency of cleaning services and increased hygiene.', ['Data Sharing Coalition'], {name: 'Data Sharing Coalition', email: 'info@datasharingcoalition.eu'}, ['Facility Management'], '2021', 'https://datasharingcoalition.eu/2021/findings-use-case-smart-cleaning/', ['Process'], ['Processed data'], ['Customer-provided'], ['Confidential'], ['Non-PII-relevant'], ['Organizational'], ['(Near-) realtime'], ['Economic'], ['Cross-industry'], ['Financial'], null, ['Data consumer'], ['Closed API'], ['Technical', 'Legal'], ['Agreement-based'], ['Continuous'], ['Primary'], ['Many-to-one'], ['Efficiency gains', 'Improved quality'], ['Consumer-initiated'], ['Consumer-controlled']),
    new Usecase('Global Open Data for Agricultureand Nutrition (GODAN) Action', 'he Global Open Data for Agriculture and Nutrition (GODAN) Action initiative is focused on making agricultural and nutritionally relevant data available, accessible, and usable worldwide to support global efforts for food security. The Open Data Institute (ODI) is a partner in the initiative and aims to help sectors maximize value from data through its expertise in learning, innovation, and infrastructure. GODAN Action is led by Wageningen University and Research and is supported by the UK Department for International Development. The initiatives focus is on increasing farmers yields in developing countries.', ['Open Data Institute', ' GODAN iniative'], {name: 'Open Data Institute', email: 'info@theodi.org'}, ['Agriculture, Nutrition'], '2018', 'https://theodi.org/project/global-open-data-for-agriculture-and-nutrition-godan-action/', ['Environment'], ['Enriched data'], ['Generated', 'Free available'], ['Confidential'], ['Non-PII-relevant'], ['Shared'], ['Up-to-Date'], ['Economic', 'Social & Ecological'], ['Same industry'], ['Other'], ['Free'], ['Intermediary'], ['Platform'], ['Technical'], ['Open'], ['Continuous'], ['Primary'], ['Many-to-many'], ['New insights'], null, ['Provider-controlled']),
    new Usecase('Greater London Authority Datastore - Covid-19', 'The Greater London Authority Datastore published the COVID-19 Mobility Report, a resource updated daily that provides insight into changing mobility dynamics in London. The report is powered by six private and public-sector mobility datasets and offers a case study of how the public sector can adopt new data sources in times of urgency. The London Datastore, which hosts the report, is an open-source platform containing over 6,000 datasets relevant to the city of London. The Datastore provides additional information and context on how the data can be used for civic and economic purposes. The COVID-19 Mobility Report provides awareness on five key metrics tied to mobility and is updated daily with static visualizations and downloadable datasets.', ['Open Data Institute', ' The Gov Lab', ' Quebiq', ' Google', ' Apple', ' Purple', ' etc. '], {name: 'Open Data Institute', email: 'info@theodi.org'}, ['Healthcare'], '2021', 'https://theodi.org/wp-content/uploads/2021/04/4-Greater-London-Authority-Datastore_v2.pdf', ['Product'], ['Processed data'], ['Generated'], ['Sensitive'], ['PII-relevant'], ['Individual'], ['(Near-) realtime'], ['Social & Ecological', 'Economic'], ['Cross-industry'], ['Other', 'Data'], ['Free'], ['Intermediary'], ['Platform'], ['Semantic', 'Technical'], ['Open'], ['Continuous'], ['Primary'], ['Many-to-many'], ['Efficiency gains', 'New insights'], null, ['Provider-controlled']),
    new Usecase('Final deliverable Green Loans', 'The use of external data and the diversification of services in the mortgage domain is becoming increasingly relevant to sustainability. Financial Service Providers (FSPs) require a lot of data from consumers for loan application assessments, and the use of structured data from external sources is becoming common for faster and more reliable loan applications. Smart meter data is critical for the energy transition, with increasing availability of energy usage data due to the adoption of smart meters. DSOs steward smart meter data and are looking to enable new applications for consumer benefit. FSPs can use smart meter data to develop propositions that help customers make their homes more energy-efficient, contributing to their own green ambitions and creating extra relevance for their customers. In this use case, the DSO shares smart meter data with the FSP on behalf of the consumer with their consent.', ['Data Sharing Coalition', ' HDN', ' EDSN'], {name: 'Data Sharing Coalition', email: 'info@datasharingcoalition.eu'}, ['Energy'], '2021', 'https://datasharingcoalition.eu/2021/findings-green-loans-use-case/', ['Human'], ['Processed data'], ['Customer-provided'], ['Sensitive'], ['PII-relevant'], ['Individual'], ['(Near-) realtime'], ['Economic', 'Social & Ecological'], null, ['Other'], ['Free'], ['Data consumer'], ['Platform'], ['Legal'], ['Agreement-based'], ['Continuous'], ['Primary'], ['Many-to-one'], ['Efficiency gains', 'New insights'], ['Consumer-initiated'], ['Provider-controlled']),
    new Usecase('Unattended home delivery by controlled and scalable data sharing', 'Merchants and logistic service providers (LSPs) are facing challenges in meeting customer expectations and reaching profitability in home delivery. The growth of online shopping is expected to continue, with a YoY growth of 7.5 to 15%. Food delivery is expected to reach a market size of EUR 10 billion in 2025, but is even loss-making for merchants. Unattended home delivery of groceries using smart locked doors is a solution being explored, with 33% of households open to the idea. Innovation in home delivery services by merchants and LSPs, such as tokenized payments and local food initiatives, is needed to create value for consumers and stay relevant in the market.', ['Data Sharing Coalition', ' iShare', ' The Chain Never Stops', ' Poort8'], {name: 'Data Sharing Coalition', email: 'info@datasharingcoalition.eu'}, ['Home delivery'], '2022', 'https://datasharingcoalition.eu/2022/findings-use-case-unattended-home-delivery-by-controlled-and-scalable-data-sharing/', ['Process'], ['Processed data'], ['Customer-provided'], ['Sensitive'], ['PII-relevant'], ['Individual'], ['(Near-) realtime'], ['Economic'], ['Cross-industry'], ['Financial'], null, ['Intermediary'], null, ['Technical', 'Legal'], ['Application-based'], ['Event-based'], ['Primary'], ['Many-to-many'], ['Efficiency gains'], null, null),
    new Usecase('How data access can support innovation in agriculture', 'The ODI is working with CABI and the Bill & Melinda Gates Foundation to support country-led inclusive agricultural transformation by enabling access to data in sub-Saharan Africa and south Asia. Poverty in these areas is caused by environmental, economic, and social factors including low profitability for smallholder farmers, and lack of opportunities and resources for women. The foundation aims to increase the income of smallholder farmers, especially women, by providing access to digitally-enabled services. By 2030, the foundation aims to have 50% of smallholder farmers in target areas have access to these services. The ODI has been working on overcoming challenges in accessing and sharing data, developing engagement strategies and a toolbox to provide FAIR data for grant-funded projects.', ['Open Data Institute', ' CABI', ' Bill & Melinda Gates Foundation'], {name: 'Open Data Institute', email: 'info@theodi.org'}, ['Agriculture'], '2020', 'https://theodi.org/article/how-data-access-can-support-innovation-in-agriculture/', null, null, ['Generated'], ['Confidential'], ['Non-PII-relevant'], ['Organizational'], null, ['Social & Ecological'], ['Same industry'], ['Data', 'Service'], null, null, null, ['Semantic', 'Organizational', 'Legal'], null, null, ['Secondary'], ['Many-to-many'], ['Improved quality', 'Efficiency gains'], null, null),
    new Usecase('Collaboration between IDSA and NTT Com to Link Japanese Smart Data Platform and Europe’s GAIA X', 'The IDSA and NTT Com have started a collaboration to develop a global, secure data-management platform. The collaboration will include tests to ensure interoperability between locally organized data platforms worldwide and to assess the practicality and operability of data access rights. The test environment in Japan will be connected to two test environments in Europe for data sharing and exchange across national borders. The global data management platform will be jointly developed by Japanese and overseas companies and organizations and will ensure the rights of data providers and owners are protected. The ultimate aim of the collaboration is to contribute to a smart world by providing a platform for sharing and exchanging data worldwide.', ['NTT Group', '  IDSA', ' International Dataspaces'], {name: 'Akira Sakaino', email: 'info@internationaldataspaces.org'}, ['Data-Management'], '2020', 'https://internationaldataspaces.org/collaboration-between-idsa-and-ntt-com-to-link-japanese-smart-data-platform-and-europes-gaia-x/', ['Other'], null, ['Generated'], ['Sensitive'], null, ['Organizational'], null, ['Economic'], ['Cross-industry'], null, null, ['Intermediary'], ['Platform'], ['Technical', 'Legal'], null, null, null, ['Many-to-many'], ['Efficiency gains', 'New insights'], null, null),
    new Usecase('Findings improved monitoring of human trafficking', 'Human trafficking is a major problem affecting over 40 million people globally. Combating it is limited by the lack of data collaboration due to legal and trust barriers. Multi-party computation (MPC) reduces these barriers by allowing organizations to jointly create insights from data without revealing sensitive source data to each other. MPC works by fragmenting and encrypting the source data from each organization and then performing calculations on the encrypted data. The Data Sharing Coalition created a scalable design for MPC-based data collaboration to improve the monitoring of sexual exploitation.', ['Data Sharing Coalition', ' Roseman Labs', ' Pinsent Masons', ' Sustainable Rescue'], {name: 'Data Sharing Coalition', email: 'info@datasharingcoalition.eu'}, ['Human Rights'], '2022', 'https://datasharingcoalition.eu/2022/findings-improved-monitoring-of-human-trafficking-use-case/', ['Human'], ['Processed data'], ['Generated'], ['Sensitive'], ['PII-relevant'], ['Organizational'], ['Up-to-Date'], ['Social & Ecological'], ['Cross-industry'], ['Other'], ['Free'], ['Intermediary'], ['Platform'], ['Legal'], ['Agreement-based'], ['Continuous'], ['Primary', 'Secondary'], ['Many-to-many'], ['New insights'], null, ['Intermediary-controlled']),
    new Usecase('Informes de Movilidad - Telefónica Chile and Universidad del Desarroll', 'A data-science team at the Universidad del Desarrollo (UDD) Data Science Institute in Chile used anonymized telecommunications data from Telefónica Chile to analyze mobility patterns during the early days of the COVID-19 pandemic. The resulting report was published in early April and was used to inform public policy. The data was used to measure broad patterns of mobility as peoples devices connected with different cell towers over time. The report became the primary source of intelligence for the government of Chiles policymaking on mobility restrictions, and was backed by a wide network of subject-matter experts and widespread media coverage. The project involved partnerships with Telefónica Chile, Cisco, and the Government of Chiles Ministry of Science.', ['Open Data Institute', ' Telefónica Chile', ' Government of Chiles Ministry of Science'], {name: 'Open Data Institute', email: 'info@theodi.org'}, ['Healthcare'], '2021', 'https://theodi.org/wp-content/uploads/2021/04/3-Informes-de-Movilidad_v2.pdf', ['Human'], ['Processed data'], ['Generated', 'Free available'], ['Sensitive'], ['PII-relevant'], ['Shared'], ['(Near-) realtime'], ['Social & Ecological'], ['Cross-industry'], ['Other'], ['Free'], ['Intermediary'], ['Platform'], ['Legal'], ['Trust-based'], ['Continuous'], ['Secondary'], ['Many-to-many'], ['New insights'], null, ['Provider-controlled'])
  ];
  sortedCases: Usecase[] = this.useCases;
  filCase: Usecase = new Usecase(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
  sort: string = 'new';

  updateFilCase(filCase: Usecase) {
    this.filCase = filCase;
    this.updateSortedCases();
  }

  updateSort(sort: string) {
    this.sort = sort;
    this.updateSortedCases();
  }

  updateSortedCases() {
    console.log(0);
    this.sortedCases = this.useCases;
    const fc = this.filCase;
    const so = this.sort;
    this.sortedCases = this.sortedCases.sort(function compare(a: Usecase, b: Usecase) {
      if(!isNaN(Usecase.caseSimilarity(a, fc)) && !isNaN(Usecase.caseSimilarity(b, fc))){
        if(Usecase.caseSimilarity(a, fc) < Usecase.caseSimilarity(b, fc)){
          return 1;
        }
        if(Usecase.caseSimilarity(a, fc) > Usecase.caseSimilarity(b, fc)){
          return -1;
        } else{
          if(a.year_of_publication < b.year_of_publication){
            if(so === 'new'){return 1;} else{return -1;};
          }
          if(a.year_of_publication > b.year_of_publication){
            if(so === 'new'){return -1;} else{return 1;};
          }
          else{return 0;}
        }
      }
      if(isNaN(Usecase.caseSimilarity(a, fc)) && !isNaN(Usecase.caseSimilarity(b, fc))){
        return 1;
      }
      if(!isNaN(Usecase.caseSimilarity(a, fc)) && isNaN(Usecase.caseSimilarity(b, fc))){
        return -1;
      }
      else{
        if(a.year_of_publication < b.year_of_publication){
          if(so === 'new'){return 1;} else{return -1;};
        }
        if(a.year_of_publication > b.year_of_publication){
          if(so === 'new'){return -1;} else{return 1;};
        }
        else{return 0;}
      }
    })

  }

  gotFav(usecase: Usecase){
    this.newFav.emit(usecase);
  }

  gotUnfav(usecase: Usecase){
    this.newUnfav.emit(usecase);
  }

}
